config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"
  get "home", to: "home#index"
  devise_for :users

  resources :users, only: :index do
    resources :addresses, only: %i(index new create edit update destroy) do
      post :set_primary_address, on: :member
    end

    resources :purchases, only: %i(index create) do
      get :bill, on: :collection
      resources :purchase_items, only: %i(index)
    end
  
    resources :cart_items, only: %i(index destroy)

    member do
      get :edit_password
      patch :update_password
    end
  end

  resources :courses do
    resources :cart_items, only: %i(create)
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :user_signed_in?
  before_action :authenticate_user!, only: %i(index bill)
  before_action :empty_cart, only: %i(bill, create)

  def index
    @purchases = Current.user.purchases
  end

  def bill
    @total_price = Current.cart.courses.sum(:price)
    @total_items = Current.cart.cart_items.count
    @address = Current.user.default_address
    if @address.nil?
      redirect_to users_path, warning: "Please add a primary address to purchase cart"
    end
  end

  def create
    total_price = Current.cart.courses.sum(:price)
    items = Current.cart.courses.pluck(:id, :price)

    @purchase = Current.user.purchases.create(user_id: Current.user.id, address_id: Current.address.id, total_price: total_price)

    if @purchase.nil?
      redirect_to users_path, warning: "Failed to purchase"
    end

    items.each do |course_id, price|
      purchase_item = PurchaseItem.new(course_id: course_id, price: price, purchase_id: @purchase.id)
      redirect_to users_path, warning: "Failed to complete purchase" unless purchase_item.save
    end
    PurchaseMailJob.perform_later(@purchase, Current.user)
    redirect_to users_path, success: "Purchase succesfully"
  end

  private
  def empty_cart
    redirect_to users_path, warning: "Cannot Purchase a empty cart" if Current.cart.cart_items.count == 0 
  end
end

app/views/purchases/_purchase_list.html.erb
<% @purchases.each_with_index do |purchase, index| %>
  <div class="profile-usertitle-name">
    <%= link_to "Purchase History #{index + 1}", user_purchase_purchase_items_path(user_id: Current.user.id, purchase_id: purchase.id) %>
  </div>
<% end %>

app/views/purchases/_purchases.html.erb
<div class="profile-usertitle">
  <div class="profile-usertitle-name">
    <%= "Purchase History" %>
  </div>
  <div class="addressbar">
    <%= render partial: "purchases/purchase_list" %>
  </div>
</div>
<div class="profile-usertitle">
  <div class="profile-usertitle-name">
    <%= link_to "Show all Purchase History", user_purchases_path(Current.user) %>
  </div>
</div>

app/views/purchases/bill.html.erb
<div class="bill">
  <div class="profile-usertitle">
    <div class="profile-usertitle-name">
      <%= "Bill Preview" %>
      <%= link_to "Purchase Cart", user_purchases_path(Current.user), method: :post, class: "button-address" %>
    </div>
    <div class="addressbar">
      <%= "Total Price : #{@total_price}" %>
      <%= "Total Item : #{@total_items.to_i}" %>
    </div>
    <div class="addressbar">
      <%= "Delivery address: #{@address.street}, #{@address.city}, #{@address.country}, #{@address.code}" %>
    </div>
  </div>
  <div class="profile-usertitle">
    <div class="profile-usertitle-name">
      <%= link_to "Change delivery address", user_addresses_path(Current.user) %>
    </div>
    <div class="profile-usertitle-name">
      <%= link_to "Check all Cart Items", user_cart_items_path(Current.user) %>
    </div>
  </div>
</div>

app/views/purchases/index.html.erb
<%= render partial: "shared/alert" %>

<div class="title-container">
  <h1> Purchases </h1>
</div>

<div class="adddisplay">
  <% @purchases.each_with_index do |purchase, index| %>
    <div class="addressblock">
      <div class="addresshead">
        <%= "Purchase # #{index + 1}" %>
      </div>
      <div class="addressstyle">
        <%= "Total Price: #{purchase.total_price}" %>
      </div>
      <div class="addressstyle">
        <%= link_to "View purchased items", user_purchase_purchase_items_path(user_id: Current.user.id, purchase_id: purchase.id) %>
      </div>
    </div>
  <% end %>
</div>