config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"
  get "home", to: "home#index"
  devise_for :users

  resources :users, only: :index do
    resources :addresses, only: %i(index new create edit update destroy) do
      post :set_primary_address, on: :member
    end

    resources :purchases, only: %i(index create) do
      get :bill, on: :collection
      resources :purchase_items, only: %i(index)
    end
  
    resources :cart_items, only: %i(index destroy)

    member do
      get :edit_password
      patch :update_password
    end
  end

  resources :courses do
    resources :cart_items, only: %i(create)
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :course
  validates :course_id, uniqueness: { scope: :cart_id, message: "One course per user" }
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :user_signed_in?
  before_action :authenticate_user!, only: %i(index destroy)
  before_action :set_cart_item, only: %i(destroy)  

  def index
    @course_cart_items = Current.cart.courses.zip(Current.cart.cart_items.pluck(:id))
  end

  def create
    @cart_item = CartItem.new(cart_id: Current.cart.id, course_id: params[:course_id])
    if @cart_item.save
      redirect_to courses_path, info: "Added to cart"
    else
      redirect_to course_path(params[:course_id]), info: "Already added to cart "
    end
  end

  def destroy
    @cart_item.destroy
    respond_to do |format|
      format.html { redirect_to user_cart_items_path(Current.user), info: "Cart item removed" }
      format.json { head :no_content }
      format.js   { flash.now[:danger] = "Course removed from cart" }
    end
  end

  private
  def set_cart_item
    @cart_item = Current.cart.cart_items.find_by(id: params[:id])
    redirect_to user_cart_items_path(Current.user), warning: "You are trying to access invalid Cart Item" if @cart_item.blank?
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
  def added_to_cart?(course_id)
    return true if !Current.cart.nil? && Current.cart.courses.find_by(id: course_id)
    false
  end
end

app/views/cart_items/_cart_items.html.erb
<div class="profile-usertitle">
  <div class="profile-usertitle-name">
    <%= "Cart" %>
    <%= link_to "Purchase Cart", bill_user_purchases_path(Current.user), class: "button-address" %>
  </div>
  <div class="addressbar">
    <%= render partial: "cart_items/preview_cart" %>
  </div>
</div>
<div class="profile-usertitle">
  <div class="profile-usertitle-name">
    <%= link_to "Show all Cart Items", user_cart_items_path(Current.user) %>
  </div>
</div>

app/views/cart_items/_preview_cart.html.erb
<% @courses.each do |course| %>
  <div class="profile-usertitle-name">
    <%= "Item: #{course.name}, Price: #{course.price.to_f}" %>
  </div>
<% end %>

app/views/cart_items/destroy.js.erb
$('.remove').bind('ajax:success', function(){
  $(this).closest('tr').fadeOut();
});
$("#flash").html('<%= j render partial: "shared/alert" %>');

app/views/cart_items/index.html.erb
<div id="flash">
  <% if notice.present? %>
    <%= render partial: "shared/notice_banner" %>
  <% end %>
</div>

<div class="title-container">
  <h1> Cart items </h1>
  <%= link_to "Purchase cart", bill_user_purchases_path(Current.user), class: "button" %>
</div>
<table>
  <tbody>
    <% @course_cart_items.each do |course, cart_item_id| %>
      <tr>
        <td>
          <div class="coursedisplay">
            <div class="addresshead">
              Course: 
            </div>
            <div class="addressstyle">
              <%= "Name: #{course.name}, Price: #{course.price}" %> 
            </div>
          </div>
        </td>
        <td class="btn btn-success"> <%= link_to "View Item", course_path(course.id) %> </td>
        <td class="btn btn-success"> <%= link_to "Remove Item", user_cart_item_path(user_id: Current.user.id, id: cart_item_id),
                                                            method: :delete, remote: true, class: "remove" %> </td>
      </tr>
    <% end %>
  </tbody>
</table>