config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"
  get "home", to: "home#index"
  devise_for :users

  resources :users, only: :index do
    resources :addresses, only: %i(index new create edit update destroy) do
      post :set_primary_address, on: :member
    end

    resources :purchases, only: %i(index create) do
      get :bill, on: :collection
      resources :purchase_items, only: %i(index)
    end
  
    resources :cart_items, only: %i(index destroy)

    member do
      get :edit_password
      patch :update_password
    end
  end

  resources :courses do
    resources :cart_items, only: %i(create)
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :user_signed_in?
  before_action :authenticate_user!
  before_action :authenticate_address!, only: %i(edit update destroy set_primary_address)

  def index
    @addresses = Current.user.addresses
  end

  def new
    @address = Current.user.addresses.new
  end

  def create
    @address = Current.user.addresses.new(address_params)
    if @address.save
      redirect_to user_addresses_path(Current.user), success: "Address added successfully"
    else
      flash.now[:danger] = "Failed to add address"
      render :new
    end
  end

  def set_primary_address
    Current.user.update(default_address_id: @address.id)
    respond_to do |format|
      format.html { redirect_to user_addresses_path(Current.user), success: "Primary Address Set" }
      format.json { head :no_content }
      format.js { flash.now[:success] = "Primary address Set" }
    end
  end

  def edit; end

  def update
    if @address.update(address_params)
      redirect_to user_addresses_path(Current.user), success: "Address Updated"
    else
      flash.now[:danger] = "Failed to update address"
      render :edit
    end
  end

  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to user_addresses_path(Current.user), warning: "Address Deleted" }
      format.json { head :no_content }
      format.js   { flash.now[:danger] = "Address Deleted" }
    end
  end

  private

  def address_params
    params.require(:address).permit(:street, :city, :state, :country, :code)
  end

  def authenticate_address!
    @address = Current.user.addresses.find_by(id: params[:id])
    redirect_to user_addresses_path, warning: "You are trying to access invalid address" if @address.blank?
  end
end

app/views/addresses/_addresses.html.erb
<div class="profile-usertitle">
  <div class="profile-usertitle-name">
    <%= "Addresses" %>
    <%= link_to "Add Address", new_user_address_path(Current.user), class: "button-address" %>
  </div>
  <div class="addressbar">
    <%= render partial: "addresses/preview_addresses" %>
  </div>
</div>
<div class="profile-usertitle">
  <div class="profile-usertitle-name">
    <%= link_to "Show all addresses", user_addresses_path(Current.user) %>
  </div>
</div>

app/views/addresses/_preview_addresses.html.erb
<% @addresses.each do |address| %>
  <div class="profile-usertitle-name">
    <%= "Address: #{address.street}, #{address.city}, #{address.code}" %>
  </div>
<% end %>
<div class="addressstyleprimary">
  <%= "Primary Address: #{Current.address.street}, #{Current.address.country}, #{Current.address.code}" if !Current.address.nil? %>
</div>

app/views/addresses/destroy.js.erb
$('.delete').bind('ajax:success', function(){
  $(this).closest('tr').fadeOut();
  $("#prime").load(location.href + " #prime");
});
$("#flash").html('<%= j render partial: "shared/alert" %>');

app/views/addresses/edit.html.erb
<%= render partial: "shared/alert" %>
<%= form_with model: @address, url: user_address_path(user_id: Current.user.id, id: @address.id), method: :patch do |address| %>
  <%= render partial: "shared/error_messages", locals: { object: @address } %>
  <div class="form-section">
    <%= address.label("Street") %>
    <%= address.text_area :street %>
    <%= address.label("City") %>
    <%= address.text_field :city %>
    <%= address.label("State") %>
    <%= address.text_field :state %>
    <%= address.label("Country") %>
    <%= address.text_field :country %>
    <%= address.label("Postal Code") %>
    <%= address.number_field :code %>
    <%= address.submit "Update", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/addresses/index.html.erb
<div id="flash">
  <% if notice.present? %>
    <%= render partial: "shared/notice_banner" %>
  <% end %>
</div>

<div class="title-container">
  <h1> Addresses </h1>
  <%= link_to "Add a new Address", new_user_address_path(Current.user), class: "button" %>
</div>

<div class="adddisplay">
  <div class="addressblock">
    <div class="addresshead">
      Primary address:
    </div>
    <div class="addressstyle" id="prime">
      <%= "#{Current.address.street}, #{Current.address.country}, #{Current.address.code}" if !Current.address.nil? %>
    </div>
  </div>
  <table>
  <tbody>
  <% @addresses.each do |address| %>
      
      <tr>
        <td class="addressblock"> 
          <div class="addresshead">
            Address:
          </div>
          <div class="addresstyle">
          <%= "#{address.street}, #{address.city}, #{address.state}, #{address.country}, #{address.code}" %>
          </div>
        </td>
        <td class="btn btn-success"> <%= link_to "Edit Address", edit_user_address_path(user_id: Current.user.id, id: address.id) %> </td> 
        <td class="btn btn-success"> <%= link_to "Delete Address", user_address_path(user_id: Current.user.id, id: address.id),
                                                          method: :delete, remote: true, class: "delete" %> </td> 
        <td class="btn btn-success"> <%= link_to "Set as Primary Address", set_primary_address_user_address_path(user_id: Current.user.id, id: address.id),
                                                          method: :post, remote: true, class: "primary" %> </td> 
      </tr>
  <% end %>
  </tbody>
  </table>
</div>

app/views/addresses/new.html.erb
<%= render partial: "shared/alert" %>
<%= form_with model: @address, url: user_addresses_path(Current.user), method: :post do |address| %>
  <%= render partial: "shared/error_messages", locals: { object: @address } %>
  <div class="form-section">
    <%= address.label("Street") %>
    <%= address.text_area :street %>
    <%= address.label("City") %>
    <%= address.text_field :city %>
    <%= address.label("State") %>
    <%= address.text_field :state %>
    <%= address.label("Country") %>
    <%= address.text_field :country %>
    <%= address.label("Postal Code") %>
    <%= address.number_field :code %>
    <%= address.submit "Add", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/addresses/set_primary_address.js.erb
$('.primary').bind('ajax:success', function(){
  $("#prime").load(location.href + " #prime");
});
$("#flash").html('<%= j render partial: "shared/alert" %>');