config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"
  get "home", to: "home#index"
  devise_for :users

  resources :users, only: :index do
    resources :addresses, only: %i(index new create edit update destroy) do
      post :set_primary_address, on: :member
    end

    resources :purchases, only: %i(index create) do
      get :bill, on: :collection
      resources :purchase_items, only: %i(index)
    end
  
    resources :cart_items, only: %i(index destroy)

    member do
      get :edit_password
      patch :update_password
    end
  end

  resources :courses do
    resources :cart_items, only: %i(create)
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  Contact Us :- 9878654531
  <br>
  elearing@edu.bussiness.io
  <div class="footer-field ml-right">
    <div class="footer-item ">
      <p> &#169; eLearning corporation INDIA</p>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
<%= link_to image_tag("logos/logo.png", width: '300px'), home_path %>
  <% if user_signed_in? %>
    <div class="nav-field">
      <div class="nav-item">
        <%= link_to "Home", home_path %>
      </div>
      <div class="nav-item">
        <%= link_to "Courses", courses_path %>
      </div>
      <%= "Logged in as" %>
      <div class="nav-item">
        <%= link_to "#{Current.user.email}", users_path(Current.user) %>
      </div>
      <div class="nav-item">
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      </div>
    </div>
  <% else %>
    <div class="nav-field">
      <div class="nav-item">
        <%= link_to "Home", home_path %>
      </div>
      <div class="nav-item">
        <%= link_to "Courses", courses_path %>
      </div>
      <div class="nav-item">
        <%= link_to "Login", new_user_session_path %>
      </div>
      <div class="nav-item">
        <%= link_to "Create Account", new_user_registration_path %>
      </div>
    </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>elearning</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bkg">
    <%= render partial: "layouts/navbar" %>
      <%= yield %>
    <%= render partial: "layouts/footer" %>
  </body>
</html>